from pydantic import BaseModel
from typing import List, Literal
from uuid import UUID

"""
This file defines the Pydantic schemas for responses sent by AI Assistant, used by langchain parser.
"""
class SourceQuotation(BaseModel):
    """
    Defines the schema of quoted sorces in the AI response
    """
    source_id: UUID
    source_type: str
    quoted_context: str

class AssistantResponse(BaseModel):
    """
    This schema defines the structure of response generated by AI Assistant.
    """
    question: str
    answer: str
    sources: List[SourceQuotation]
    confidence: float

class JobMatch(BaseModel):
    job_id: UUID
    job_title: str
    match_reason: str
    confidence_score: float

class RecommendationResponse(BaseModel):
    matches: List[JobMatch]

class AIRatingResponse(BaseModel):
    confidence: float
    reason: str

class ImprovementRequest(BaseModel):
    description: str
    mode: Literal["short", "detailed", "marketing"]="detailed"

class ImprovementResponse(BaseModel):
    improved_desc: str