from pydantic import BaseModel
from typing import List, Literal, Optional, Union, Any
from uuid import UUID
from app.core.enum import UserRole

"""
This file defines the Pydantic schemas for responses sent by AI Assistant, used by langchain parser.
"""
class SourceQuotation(BaseModel):
    """
    Defines the schema of quoted sorces in the AI response
    """
    source_id: UUID
    source_type: str
    quoted_context: str

class AssistantResponse(BaseModel):
    """
    This schema defines the structure of response generated by AI Assistant.
    """
    question: str
    answer: str
    sources: List[SourceQuotation]
    confidence: float

class JobMatch(BaseModel):
    """
    Represents a recommended job match for a candidate.
    Contains job ID, title, reason for the match, and confidence score.
    """
    job_id: UUID
    job_title: str
    match_reason: str
    confidence_score: float

class RecommendationResponse(BaseModel):
    """
    Holds a list of job matches returned as recommendations.
    """
    matches: List[JobMatch]

class AIRatingResponse(BaseModel):
    """
    Represents the AI's rating for a job recommendation.
    Includes confidence score and a short reason.
    """
    confidence: float
    reason: str

class ImprovementRequest(BaseModel):
    """
    Input schema for requesting an improved job description.
    'mode' controls the style: short, detailed, or marketing.
    """
    description: str
    mode: Literal["short", "detailed", "marketing"]="detailed"

class ImprovementResponse(BaseModel):
    """
    Contains the improved job description generated by the AI.
    """
    improved_desc: str

class ApiCallInput(BaseModel):
    """
    Defines input for an API call action from the AI agent.
    Currently supports endpoints for jobs or companies.
    """
    endpoint: Literal["/jobs/", "/companies/"]
    # params: dict

class VectorSearchInput(BaseModel):
    """
    Input for a vector database search by the AI agent.
    Includes the entity type, search query, and number of top results.
    """
    entity_type: Literal["job", "candidate_resume", "company"]
    query: str
    top_k: int=5

class ReasoningInput(BaseModel):
    """
    Input for LLM-based reasoning tasks.
    Contains the task description and optional context data.
    """
    task: str
    context: dict

class AgentResponse(BaseModel):
    """
    Structure of a response from the AI agent.
    Includes safety check, intent, action type, action input, state, and optional output.
    """
    safety: Literal["allowed", "not_allowed"]
    intent: str
    action_type: Optional[Literal["api_call", "search_vector_db", "llm_reasoning_tool", "none"]]
    action_input: Optional[Union[ApiCallInput, VectorSearchInput, ReasoningInput]]
    state: Literal["CONTINUE", "FINAL"]
    output: Optional[Any]

class UserContext(BaseModel):
    """
    Represents the context of the user interacting with the AI agent.
    Includes user ID, role, and authentication token.
    """
    user_id: UUID
    role: UserRole
    access_token: str
